# GitHub Pages configuration for Acosta Landscaping and Construction
title: "Acosta Landscaping and Construction"
description: "Professional landscaping, hardscaping, fence installation, and outdoor construction services"
url: ""  # Will be set automatically by GitHub Pages
baseurl: ""  # Will be set automatically by GitHub Pages

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - .git/

# Include files that start with underscores
include:
  - _config.yml

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: en_US
author: "Acosta Landscaping and Construction"
twitter:
  username: ""  # Add your Twitter handle if you have one
facebook:
  publisher: ""  # Add your Facebook page if you have one

# Site verification (add these if you use Google Analytics, etc.)
google_analytics: ""  # Add your GA tracking ID if you have one
google_site_verification: ""  # Add your Google site verification if you have one
